### PR TITLE
Fix cover fetch when it has single or doublequotes in its path

### PR DESCRIPTION
**Pull request by KeitIG**

### CODE REVIEW

**Comment by YurySolovyov** [comment]
Aren't there node path's helpers that will do the job?

**Comment by KeitIG** [comment]
didn't find any

**Comment by KeitIG** [comment]
god, I don't know why Travis is still building!

**Comment by KeitIG** [comment]
k, it should be fixed

**Comment by YurySolovyov** [comment]
We may need to disable it on it's dashboard

**Pull request merged**
