### PR TITLE
Fix up, down, and enter keys in tracklist

### PR DESCRIPTION
**Pull request by dkniffin**
#292

### CODE REVIEW

**Comment by YurySolovyov** [comment]
Heh, are there any eslint rules for that?

**Comment by KeitIG** [comment]
I guess not. Eslint wouldn't know if it's a static method or not.

**Comment by dkniffin** [comment]
It wouldn't help with this problem, but there's [this](http://eslint.org/docs/rules/consistent-return)

**Comment by YurySolovyov** [comment]
maybe this one http://eslint.org/docs/rules/array-callback-return ?

**Comment by dkniffin** [comment]
Good find, @YurySolovyov! That caught it. I added the config for it.

**Comment by KeitIG** [comment]
Thanks for the fix.

**Pull request merged**
