### PR TITLE
Add min/max window controls

### PR DESCRIPTION
**Pull request by dkniffin**
#41

image

### CODE REVIEW

**Comment by YurySolovyov** [comment]
How about screenshot with native frame?

**Comment by dkniffin** [comment]
With the native frame, it doesn't show up at all.

image

**Comment by YurySolovyov** [comment]
LGTM, thought you need to wait for @KeitIG's :+1:

**Comment by KeitIG** [comment]
I'll review it asap

**Comment by dkniffin** [comment]
@KeitIG I'm fine with the width, font-size and height changes, but I think the `active` state should stay. It feels weird to have a button that doesn't react when pressed, and it doesn't match the behavior of other windows.

**Comment by YurySolovyov** [comment]
I like how atom does it
Dark:
image
Light:
image

**Comment by KeitIG** [comment]
@dkniffin Ye, I should have precised it was because this active state in particular was not relevant/sexy anymore. I'll add one later.

@YurySolovyov If you find sexier icons, don't hesitate to poke me as the one from FA are not really great.

**Comment by YurySolovyov** [comment]
Ones [you mentioned here](https://github.com/KeitIG/museeks/issues/41#issuecomment-240143430) were looking nice, not much else I can think of.
Maybe we'll be able to extract just minimum required svg code if we choose to use them

**Comment by KeitIG** [comment]
I edited my review with some more things to check

**Comment by YurySolovyov** [comment]
I just found that while initial partial screens look ok, when looking at full-sized one, current it looks weird and oversized.

**Comment by dkniffin** [comment]
I'll finish this up soon. I tried re-importing my library and ran into #135, and haven't been using Museeks much in the past week or so. But @KeitIG pointed me at the branch with the fix, so I should be able to do this now.

**Comment by KeitIG** [comment]
@dkniffin bump :)

**Comment by dkniffin** [comment]
@KeitIG Hey. I don't remember where I left off on this. I probably won't have time soon to finish it out, so would you mind finishing it?

**Comment by KeitIG** [comment]
should be in my power

**Comment by KeitIG** [comment]
Closing this, will re-open a new one.

**Pull request closed without merging**
