### PR TITLE
Add player functions to tray

### PR DESCRIPTION
**Pull request by dkniffin**
screen shot 2016-11-19 at 11 05 44 pm

This is a step from #253

### CODE REVIEW

**Comment by KeitIG** [comment]
Thanks for your PR:

- can you make the play-pause Dynamic ? Like when a track is playing, it shows pause only, and vice versa ?
- rename prev to previous
- remove the icons: on some OS (windows, some linux distributions), the tray menu is white, so the icons would not be visible

**Comment by dkniffin** [comment]
I'll take care of this, but I'm gonna wait until #254 is merged, because it's hard to work on this one until the tray works right.

**Comment by KeitIG** [comment]
Ready to be continued :) enjoy conflicts :p

**Comment by dkniffin** [comment]
Alright, done. New screenshot:

screen shot 2016-11-20 at 8 07 24 pm

**Comment by KeitIG** [comment]
Thanks for the work !

**Pull request merged**
