### PR TITLE
Fix PageDown, PageUp, End and Start keys on TracksList

### LINKED ISSUE #306: Page up, page down, home, end in library view
We should add support for these keys in the library view, for quicker movement without a mouse. Page up/down would move one page up/down. Home would go to the top of the library. End would go to the bottom.

### PR DESCRIPTION
**Pull request by KeitIG**
Fix  #306

### CODE REVIEW

**Comment by YurySolovyov** [comment]
I guess tabIndex was for focusing plain divs or something

**Comment by KeitIG** [comment]
I believe it was for some custom behaviors, but I cannot remember what exactly. But it was blocking the default behavior of scrollable divs, some I am a bit annoyed.

**Comment by KeitIG** [comment]
Yeah right, arrow keys do not work anymore. I will fix that.

**Comment by KeitIG** [comment]
So yeah, I attached the whole event to  `document` instead of the container, it works, I hope I didn't miss a case, lgtm though.

**Comment by YurySolovyov** [comment]
btw, there is a https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView for the case where selected row is outside the viewport and you want to make sure it is shown.

**Comment by KeitIG** [comment]
Interesting, I will play with it to see what it can do.

Thx for the review!

**Pull request merged**
