### PR TITLE
Dark tray icon option

### PR DESCRIPTION
**Pull request by a2nt**
tray icon will be updated on application restart
screenshot from 2018-02-06 18-32-44
screenshot from 2018-02-06 18-33-00
screenshot from 2018-02-06 18-33-19

### CODE REVIEW

**Comment by YurySolovyov** [comment]
1. I think current icon works ok on both themes
2. There are a lot of style changes in this PR, which makes it hard to understand where all the interesting bits are happening

**Comment by a2nt** [comment]
Sure will create the other pull request

**Comment by KeitIG** [comment]
@a2nt Btw, I am really interested in having two monochromatic icon for Museeks (one white and white black) to use as a Tray icon as they are far more elegant.

**Comment by a2nt** [comment]
I have updated commit plz remove this one

**Pull request closed without merging**
