### PR TITLE
Clean up styling of settings checkboxes

### LINKED ISSUE #221: Sexify checkboxes in settings view
They are a bit sad.
- we can use ::after/::before with custom icons
- or react-toggle http://aaronshaf.github.io/react-toggle/ + custom styling

### PR DESCRIPTION
**Pull request by dkniffin**
Fixes #221

### Before:
screen shot 2016-11-18 at 11 19 56 pm

### After:
screen shot 2016-11-18 at 11 13 40 pm

### CODE REVIEW

**Comment by KeitIG** [comment]
I like that ! Well done sir.

I'll merge this, but this is not what the issue was about ;) On mac, checkboxes are sexy, not on Win32 or Linux. The issue is about to get a similar icon for the three OS.

I made some review comments though ;)

**Comment by dkniffin** [comment]
@KeitIG Oh, ok. I didn't realize that was the intention. I can work on get a standard icon for all 3 environments.

I don't see your review comments.

**Comment by KeitIG** [comment]
You might be able to see my comments now.

About the checkboxes, if you can make then, that's cool, just do a square div with the ``::after` pseudo element and put http://fontawesome.io/icon/check/ in it when `:checked`

Basically, steal it from Atom ;)

**Comment by dkniffin** [comment]
Alright, they're manually styled using FA checks now:

screen shot 2016-11-19 at 4 57 29 pm

However, there is a tiny bug, which is: when you check the box, the text moves slightly. I don't have time right now to figure out what's causing it.

**Comment by KeitIG** [comment]
I'll do the fixes, don't worry, just correct the last error given by the build and I'll merge it :) 

````
C:\projects\museeks\src\js\components\Settings\CheckboxSetting.react.js
  36:25  error  Empty components are self-closing  react/self-closing-comp
```

**Comment by YurySolovyov** [comment]
just my 0.02$, but these checkboxes look really weird.

**Comment by Suriteka** [comment]
I agree with @YurySolovyov.
I'll try to create some cool checkboxes if you want. 😉

**Comment by KeitIG** [comment]
They do, but it should be a check in a square, not the square-check icon from FA

**Comment by KeitIG** [comment]
You know what @dkniffin, could you just revert your last commit, I'd like to handle it myself if it does not bother you :)

**Comment by dkniffin** [comment]
Done.

**Comment by KeitIG** [comment]
Thank you, great job !

**Comment by KeitIG** [comment]
For those wondering, here's the final design

screenshot from 2016-11-20 02 55 04
screenshot from 2016-11-20 02 55 25

**Pull request merged**
