### PR TITLE
Always show tray, tray>quit quits entire app

### LINKED ISSUE #238: beforeunload handler causes app to close on refresh from DevTools
I tracked it down to this: [bc7b401](https://github.com/KeitIG/museeks/commit/bc7b401fd588c6bd58254fc022230b6ba9d2d749#diff-903dcab71c64a976160e32af8a47868fR77)

``` js
window.addEventListener('beforeunload', (e) => {
    // See http://electron.atom.io/docs/api/browser-window/#event-close
    e.returnValue = false;
    this.app.close();
});
```

We should find a better way to do this.

### PR DESCRIPTION
**Pull request by dkniffin**
Fixes #238

### CODE REVIEW

**Comment by dkniffin** [comment]
@KeitIG I believe that functionality was already built into the app. Unless I'm misunderstanding, that's how it seems to work now.

**Comment by KeitIG** [comment]
Go in settings -> Interface -> use native frame.

Then when I click on the close native button, the app closes when it should minimize to tray. If you don't know how to do this I can do it if you want.

**Comment by dkniffin** [comment]
Oh! I see. Sorry, I didn't see that setting. I'll see if I can figure this out.

**Comment by KeitIG** [comment]
Great, if you don't know how to deal with it, just ask.

ref: http://electron.atom.io/docs/api/browser-window/#event-close

**Comment by dkniffin** [comment]
@KeitIG Alright, I made some more changes. I _think_ it meets all the requirements you mentioned. The one thing I wish it would do that I couldn't quite figure out is when you right click in the dock, and click "quit", it should be the same as quit from tray, but instead, it doesn't close it.

**Comment by KeitIG** [comment]
Ok, check the errors given by the CI build and I think we're good to go

**Comment by dkniffin** [comment]
Done.

**Comment by dkniffin** [comment]
I also added `bindEvents` back, because I think it could be useful later. I was actually about to use it for the other tray actions.

**Comment by KeitIG** [comment]
Can you fix the build errors ?

see https://travis-ci.org/KeitIG/museeks/builds/177480653

**Comment by dkniffin** [comment]
Yep, sorry about that. I've also installed the atom-eslint plugin, so I should see these errors before commiting.

**Comment by KeitIG** [comment]
You can use npm run lint to check that locally too

**Comment by dkniffin** [comment]
Yea, I just forget to do it 😝

**Comment by KeitIG** [comment]
Let's go.

**Pull request merged**
