### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by KeitIG**
- [x] Rename `src/js` to `src/ui`
- [x] Two indent spaces vs four? (the debate is open, I usually use 4, but most of projects I have seen use 2, in JS at least, and it allows more html nesting)
- [ ] ~Update `react-router` to v4 (#349)~
- [ ] ...

### CODE REVIEW

**Comment by YurySolovyov** [comment]
2 spaces :+1:, given we have a lot of whitespace anyway

**Comment by YurySolovyov** [comment]
Also, I'd take a look at some of the long lines wrapping we did, maybe some will fit into line length limit now.

**Comment by YurySolovyov** [comment]
Also, IMO it would be better to update react router in a separate pr. Easier to review

**Comment by KeitIG** [comment]
Well, I think we're good now. There were some component that could have been splitted, I will do it later when I have time. Codebase looks better anyway.

**Pull request merged**
